'''
Created on Nov 22, 2010

@author: Peter

Modified on May 16, 2016 by shawn
'''
from numpy import *
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import smo_kernel as smok

xcord0 = []
ycord0 = []
xcord1 = []
ycord1 = []
markers =[]
colors =[]
fr = open('testSet.txt')#this file was generated by 2normalGen.py
for line in fr.readlines():
    lineSplit = line.strip().split('\t')
    xPt = float(lineSplit[0])
    yPt = float(lineSplit[1])
    label = int(lineSplit[2])
    if (label == -1):
        xcord0.append(xPt)
        ycord0.append(yPt)
    else:
        xcord1.append(xPt)
        ycord1.append(yPt)

fr.close()
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(xcord0,ycord0, marker='s', s=90)
ax.scatter(xcord1,ycord1, marker='o', s=50, c='red')

# calculate separate plane using smo_platt
x, y = smok.load_data('testSet.txt')
a, b = smok.smo_platt(x, y, 0.6, 0.001, 40)
w = dot(x.T, a * y)

x = arange(-2.0, 12.0, 0.1)
y = (-float(w[0])*x - float(b))/float(w[1])
ax.plot(x,y)
ax.axis([-2,12,-8,6])
plt.show()