'''
Created on Nov 22, 2010

@author: Peter

Modified on May 16, 2016 by shawn
'''
from numpy import *
import matplotlib.pyplot as plt
import smo_kernel as smok
import test_toolkit as toolkit

xcord0 = []
ycord0 = []
xcord1 = []
ycord1 = []
markers =[]
colors =[]
fr = open('test_data/testSet.txt')  # this file was generated by 2normalGen.py
for line in fr.readlines():
    lineSplit = line.strip().split('\t')
    xPt = float(lineSplit[0])
    yPt = float(lineSplit[1])
    label = int(lineSplit[2])
    if (label == -1):
        xcord0.append(xPt)
        ycord0.append(yPt)
    else:
        xcord1.append(xPt)
        ycord1.append(yPt)

fr.close()
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(xcord0,ycord0, marker='s', s=90)
ax.scatter(xcord1,ycord1, marker='o', s=50, c='red')

# calculate separate plane using smo_platt
data_matrix = toolkit.load_data('test_data/testSet.txt')
x, y = toolkit.separate_x_y(data_matrix)
a, b = smok.smo_platt(x, y, 0.6, 0.001, 40)
w = dot(x.T, a * y)

x = arange(-2.0, 12.0, 0.1)
y = (-float(w[0])*x - float(b))/float(w[1])
ax.plot(x,y)
ax.axis([-2,12,-8,6])
plt.show()